### ISSUE TITLE
why mocha dependency?

### ISSUE THREAD

**Issue by gcanti** [buildo/eslint-plugin-no-copy-paste-default-export#1]
disclaimer: eslint-plugin noob

``` json
"dependencies": {
  "mocha": "^2.2.5"
}
```

**Comment by giogonzo** [comment]
indeed, a missed `--save-dev`

thanks!

Fixed and published [v0.0.3](https://github.com/buildo/eslint-plugin-no-copy-paste-default-export/releases/tag/v0.0.3)
